### PR TITLE
Work with higher level resize methods instead of getFormattedImage

### PR DESCRIPTION
**Pull request by stecman**
#17 raises an issue where a generate*Image method in a module has arguments that differ to the template-facing API, causing incorrect behaviour when used in a responsive image set. The arguments for the image resize methods exposed in templates (`$Image.CroppedImage`, `$Image.PaddedImage`, etc) are more appropriate for configuration via YAML as their parameters must be scalar to be used in a template.

This change has the bonus of keeping the configuration API for this module consistent with use of image resize methods in templates, rather than the potentially different internal API of an image resize method.

### CODE REVIEW

**Comment by xini** [comment]
Any chance we can get this merged? Cheers

**Comment by lucasfrey** [comment]
Hey @stecman,

Any reason why we haven't merged that back in the days ?

**Comment by stecman** [comment]
@lucasfrey looks like this was merged via https://github.com/heyday/silverstripe-responsive-images/pull/19, but GitHub hasn't figured that out because Loz rebased my commit. Closing :+1:

**Comment by xini** [comment]
This is not solved for the SS3 compatible version. Any chance we can get this merged?

**Comment by stecman** [comment]
Thanks @xini, I missed that before. I've tested and merged this, and released as `1.0.1`.

**Comment by xini** [comment]
Thanks so much!

**Pull request closed without merging**
