### PR TITLE
Major refactor of module

### PR DESCRIPTION
**Pull request by kinglozzer**
- Upgrade to picturefill v3.0.2
- Change YAML format to allow more than 2 arguments to be passed to image processing methods
- Change YAML format for "sizes" to <query>: <args>
- Rename "sizes" to "arguments" and "default_size" to "default_arguments" in config
- Namespace extension class

### CODE REVIEW

**Comment by kinglozzer** [comment]
I’ve made the changes suggested in #14, but removed the `HtmlEditorField`/`srcset` integration and put it in its [own module](https://github.com/bigfork/htmleditorsrcset) - upon reflection I felt it should be a separate module to this (feel free to add it to suggested modules in composer.json if you like).

**Comment by camspiers** [comment]
cc @stecman

**Comment by stecman** [comment]
@kinglozzer can you change the namespace to `Heyday\ResponsiveImages`? It's more inline with what we've got elsewhere. Happy to merge after that 👍

**Comment by kinglozzer** [comment]
@stecman Done :)

**Pull request merged**
