### PR TITLE
allow SS5

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by xini** [comment]
Thank you! Can you please tag this?

**Comment by madmatt** [comment]
Done, version `3.0.0` released: https://github.com/heyday/silverstripe-responsive-images/releases/tag/3.0.0

**Comment by xini** [comment]
Thanks!

**Comment by xini** [comment]
I would have done 2.1.0 though?

**Comment by madmatt** [comment]
While no functionality has really changed warranting a new major version number, it does provide a clear point in time - version 2 supports CMS 4, version 3 only needs to support CMS 5 going forward (so in future we may remove support for CMS 4, if the feature we want to use is only in CMS 5). It's unlikely this will happen, but I think updating our major version number to match the increase in the CMS major version number makes at least some kind of sense :)

**Comment by xini** [comment]
No worries. My thinking is that when you drop support for 4 you'll have to do a new major anyway. So right now, it's just adding compatibility, but then it breaks on the current major.

**Pull request merged**
